create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  user_id text,
  latitude double precision not null,
  longitude double precision not null,
  issue_type text not null,
  category text,
  report_type text,
  description text not null,
  intelligence_briefing text,
  location text,
  safety_rating integer default 3,
  time_cycle text default 'Day',
  image_url text,
  reported_by text not null default 'Anonymous',
  status text not null default 'PROVISIONAL', -- 'PROVISIONAL', 'CORROBORATED', 'VERIFIED', 'EXPIRED'
  corroboration_count integer not null default 0,
  negative_count integer not null default 0,
  has_evidence boolean not null default false,
  evidence_url text,
  additional_info jsonb default '[]'::jsonb,
  created_at timestamp with time zone default now()
);

-- Table for user corroboration/validation responses (enforces anti-abuse & duplicate prevention)
create table if not exists public.report_corroborations (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.community_reports(id) on delete cascade,
  user_id text not null,
  response_type text not null, -- 'SIMILAR', 'NOT_OBSERVED', 'ADDITIONAL_INFO'
  additional_info text,
  created_at timestamp with time zone default now(),
  constraint unique_user_report_response unique (report_id, user_id)
);

