"""
convert_and_predict.py - SafeStreets Audio Converter and Predictor Wrapper

Takes any input audio file (WAV, WEBM, OGG, MP3, etc.), explicitly converts/resamples it
to 16,000 Hz, 1-channel mono, 1.0 second WAV format (16,000 samples), and calls predict_audio()
from the untouched predict_voice.py script. Cleans up temporary files afterwards.
"""

import os
import sys
import json
import uuid
import argparse
import subprocess
import numpy as np
import librosa
import soundfile as sf

# Import predict_audio directly from untouched predict_voice.py
from predict_voice import predict_audio

def convert_to_16k_mono_wav(
    input_path: str,
    output_path: str,
    target_sr: int = 16000
):
    """
    Convert browser-recorded audio such as WebM/Opus into 16,000 Hz, 1-channel mono PCM WAV.
    Preserves the full recording duration without truncating to 1.0 second.
    Padding is applied ONLY if the total duration is less than 1.0 second.
    """
    target_samples = int(target_sr * 1.0)

    # Exact FFmpeg executable installed on this system.
    ffmpeg_path = r"C:\Users\jessi\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-9.0.2-full_build\bin\ffmpeg.exe"

    # FFmpeg handles WebM/Opus, OGG, MP3, WAV, etc.
    ffmpeg_cmd = [
        ffmpeg_path,
        "-y",
        "-i",
        input_path,
        "-vn",
        "-ac",
        "1",
        "-ar",
        str(target_sr),
        "-c:a",
        "pcm_s16le",
        output_path
    ]

    try:
        result = subprocess.run(
            ffmpeg_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
    except FileNotFoundError:
        raise RuntimeError(
            f"FFmpeg executable was not found at: {ffmpeg_path}"
        )

    if result.returncode != 0:
        raise RuntimeError(
            "FFmpeg audio conversion failed:\n" + result.stderr
        )

    # Read the WAV generated by FFmpeg.
    y, sr = sf.read(output_path, dtype="float32")

    # Ensure mono.
    if len(y.shape) > 1:
        y = np.mean(y, axis=1)

    # Verify sample rate.
    if sr != target_sr:
        raise RuntimeError(
            f"Unexpected sample rate after FFmpeg conversion: {sr}"
        )

    # Pad audio if total length is less than 1 second (16,000 samples)
    if len(y) < target_samples:
        padding = target_samples - len(y)
        y = np.pad(y, (0, padding), mode="constant")

    # Do NOT truncate clips > 1 second; keep the entire recording for multi-window evaluation

    # Save the final 16kHz mono WAV.
    sf.write(
        output_path,
        y,
        target_sr,
        subtype="PCM_16"
    )

    return output_path


def main():
    parser = argparse.ArgumentParser(description="Convert input audio to 16kHz mono 1s WAV and run predict_audio().")
    parser.add_argument("--audio_path", type=str, required=True, help="Path to input audio file")
    parser.add_argument("--model_path", type=str, default=r"D:\SafeStreets\safestreets2.0\voice_model.pth", help="Path to voice_model.pth")
    parser.add_argument("--metadata_path", type=str, default=r"D:\SafeStreets\safestreets2.0\model_metadata.json", help="Path to model_metadata.json")
    args = parser.parse_args()

    input_path = args.audio_path
    if not os.path.exists(input_path):
        res = {"success": False, "error": f"Input audio file not found: {input_path}"}
        print(json.dumps(res))
        sys.exit(1)

    # Temporary formatted WAV file
    temp_dir = os.path.dirname(os.path.abspath(input_path))
    formatted_wav_path = os.path.join(temp_dir, f"formatted_{uuid.uuid4().hex[:8]}.wav")

    try:
        # 1. Convert to 16kHz mono 1-second WAV
        convert_to_16k_mono_wav(input_path, formatted_wav_path)

        # 2. Run prediction using existing predict_voice.py
        result = predict_audio(formatted_wav_path, args.model_path, args.metadata_path)
        result["success"] = True
        print(json.dumps(result))

    except Exception as err:
        error_res = {
            "success": False,
            "error": f"Audio processing or prediction error: {str(err)}"
        }
        print(json.dumps(error_res))
        sys.exit(1)

    finally:
        # 3. Clean up temporary formatted WAV file
        if os.path.exists(formatted_wav_path):
            try:
                os.remove(formatted_wav_path)
            except Exception:
                pass


if __name__ == "__main__":
    main()
